<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() == 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feedback & Ratings - Admin Dashboard</title>
    <!-- Tailwind CSS -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        primary: '#4f46e5',
                        primary_dark: '#4338ca',
                        warning: '#f59e0b',
                    },
                    fontFamily: {
                        sans: ['Inter', 'sans-serif'],
                    }
                }
            }
        }
    </script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('modules/admin/css/app.css') }}">
    <!-- Cairo Font (Arabic RTL) -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap" rel="stylesheet">
    <style>
        html[dir="rtl"] body { font-family: 'Cairo', sans-serif !important; }
        html[dir="rtl"] .ml-3 { margin-left: 0 !important; margin-right: 0.75rem !important; }
        html[dir="rtl"] .ml-4 { margin-left: 0 !important; margin-right: 1rem !important; }
        html[dir="rtl"] aside { left: auto !important; right: 0 !important; border-right: none !important; border-left: 1px solid #e5e7eb !important; }
        html[dir="rtl"] .space-x-4 > :not([hidden]) ~ :not([hidden]) { --tw-space-x-reverse: 1 !important; }
        html[dir="rtl"] .space-x-2 > :not([hidden]) ~ :not([hidden]) { --tw-space-x-reverse: 1 !important; }
        html[dir="rtl"] #langDropdownMenu, html[dir="rtl"] #profileDropdownMenu { right: auto !important; left: 0 !important; }
    </style></head>
<body class="bg-gray-50 text-gray-800 font-sans antialiased overflow-hidden flex h-screen">

    @include('admin::layouts.partials.sidebar')





    <!-- Layout Wrapper -->
    <div class="flex-1 flex flex-col min-w-0 transition-all duration-300">
        
        @include('admin::layouts.partials.header')

        <!-- Main Content -->
        <main class="flex-1 p-4 sm:p-6 lg:p-8 overflow-y-auto w-full">
            
            <div class="mb-6 flex flex-col sm:flex-row justify-between items-start sm:items-center space-y-4 sm:space-y-0">
                <div>
                    <h2 class="text-2xl font-bold text-gray-900">User Real-Time Feedback</h2>
                    <p class="text-sm text-gray-500 mt-1">Monitor aggregated ratings generated by customers towards drivers and vendors.</p>
                </div>
                <div class="flex space-x-2">
                    <select id="fbFilter" class="block w-full rounded-lg border-gray-300 py-2 pl-3 pr-10 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary shadow-sm bg-white" onchange="renderTable()">
                        <option value="All">All Entities</option>
                        <option value="Driver">Driver Reviews</option>
                        <option value="Restaurant">Restaurant Reviews</option>
                        <option value="System">System/App Reviews</option>
                    </select>
                </div>
            </div>

            <!-- Dashboard Split Layout for Stats -->
            <div class="flex flex-col lg:flex-row gap-6 mb-8">
                
                <!-- Average Rating Card -->
                <div class="w-full lg:w-1/3">
                    <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6 flex flex-col items-center justify-center h-full">
                        <p class="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-2">Global Satisfaction</p>
                        <h3 class="text-6xl font-extrabold text-gray-900 mb-2">4.7</h3>
                        <div class="flex text-warning space-x-1 mb-2">
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                            <svg class="w-6 h-6 opacity-30" fill="currentColor" viewBox="0 0 20 20"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path></svg>
                        </div>
                        <p class="text-sm text-gray-500">Based on <span class="font-bold text-gray-900">4,208</span> total reviews.</p>
                    </div>
                </div>

                <!-- Star Distribution Progress Bars -->
                <div class="w-full lg:w-2/3">
                    <div class="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
                        <h4 class="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">Rating Distributions</h4>
                        <div class="space-y-3">
                            <!-- Bar 5 -->
                            <div class="flex items-center text-sm">
                                <span class="w-12 text-gray-600 font-medium whitespace-nowrap text-right pr-2">5 Stars</span>
                                <div class="w-full bg-gray-100 rounded-sm h-3 relative">
                                    <div class="bg-warning h-3 rounded-sm" style="width: 72%"></div>
                                </div>
                                <span class="w-10 text-right text-gray-500 font-medium pl-2">72%</span>
                            </div>
                            <!-- Bar 4 -->
                            <div class="flex items-center text-sm">
                                <span class="w-12 text-gray-600 font-medium whitespace-nowrap text-right pr-2">4 Stars</span>
                                <div class="w-full bg-gray-100 rounded-sm h-3 relative">
                                    <div class="bg-warning h-3 rounded-sm opacity-90" style="width: 18%"></div>
                                </div>
                                <span class="w-10 text-right text-gray-500 font-medium pl-2">18%</span>
                            </div>
                            <!-- Bar 3 -->
                            <div class="flex items-center text-sm">
                                <span class="w-12 text-gray-600 font-medium whitespace-nowrap text-right pr-2">3 Stars</span>
                                <div class="w-full bg-gray-100 rounded-sm h-3 relative">
                                    <div class="bg-warning h-3 rounded-sm opacity-70" style="width: 5%"></div>
                                </div>
                                <span class="w-10 text-right text-gray-500 font-medium pl-2">5%</span>
                            </div>
                            <!-- Bar 2 -->
                            <div class="flex items-center text-sm">
                                <span class="w-12 text-gray-600 font-medium whitespace-nowrap text-right pr-2">2 Stars</span>
                                <div class="w-full bg-gray-100 rounded-sm h-3 relative">
                                    <div class="bg-warning h-3 rounded-sm opacity-50" style="width: 3%"></div>
                                </div>
                                <span class="w-10 text-right text-gray-500 font-medium pl-2">3%</span>
                            </div>
                            <!-- Bar 1 -->
                            <div class="flex items-center text-sm">
                                <span class="w-12 text-gray-600 font-medium whitespace-nowrap text-right pr-2">1 Star</span>
                                <div class="w-full bg-gray-100 rounded-sm h-3 relative">
                                    <div class="bg-warning h-3 rounded-sm opacity-30" style="width: 2%"></div>
                                </div>
                                <span class="w-10 text-right text-gray-500 font-medium pl-2">2%</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- List Card -->
            <div class="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div class="overflow-x-auto w-full">
                    <table class="w-full whitespace-nowrap text-left text-sm text-gray-500">
                        <thead class="bg-gray-50 text-gray-700 uppercase font-semibold text-xs border-b border-gray-200">
                            <tr>
                                <th scope="col" class="px-6 py-3">Customer User</th>
                                <th scope="col" class="px-6 py-3">Entity Type</th>
                                <th scope="col" class="px-6 py-3">Rating</th>
                                <th scope="col" class="px-6 py-3">Comment Preview</th>
                                <th scope="col" class="px-6 py-3 text-right">Date</th>
                            </tr>
                        </thead>
                        <tbody id="fbTableBody" class="divide-y divide-gray-200 bg-white">
                            <!-- Populated by JS -->
                        </tbody>
                    </table>
                </div>

                <!-- Empty State -->
                <div id="emptyState" class="hidden-el p-12 flex flex-col items-center justify-center text-center border-t border-gray-200">
                    <h3 class="text-lg font-medium text-gray-900 mt-2">No feedback found</h3>
                </div>
            </div>
        </main>
    </div>

    <!-- Scripts -->
    <script src="{{ asset('modules/admin/js/app.js') }}"></script>
    <script src="{{ asset('modules/admin/js/feedback.js') }}"></script>
</body>
</html>
